module.exports = {

    MEMORY_CREEP_TYPE: 0,
    MEMORY_COOLDOWN: 1,
    MEMORY_CREEP_ACTIVITY: 2,
    MEMORY_CREEP_ACTIVITY_PAYLOAD: 3,
    MEMORY_CREEP_LAST_ACTIVITY: 6,
    MEMORY_CREEP_RESOURCE: 4,
    MEMORY_CREEP_CONTAINER: 5,

    CREEP_HARVESTER: 0,
    CREEP_BUILDER: 1,

    CREEP_ACTIVITY_IDLE:     0,
    CREEP_ACTIVITY_MOVE:     1,
    CREEP_ACTIVITY_HARVEST:  2,
    CREEP_ACTIVITY_TRANSFER: 3,

    CREEP_ACTIVITY_PAYLOAD_TARGET: 0,

    BODY_PART_LIMIT: 50

};